language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx-18mode
  - rbx-19mode
  - jruby-18mode
  - jruby-19mode
script: 'bin/dtf_test test/*/*.rb'
notifications:
  irc:
    channels:
      - "irc.freenode.org#rvm-test"
      - "irc.freenode.org#dtf-gems"
  email:
    recipients:
      - mpapis@gmail.com
      - me@deryldoucette.com
    on_failure: change
